#!/usr/bin/perl
# CGI script that creates a fill-out form
# and echoes back its values.

use CGI qw/:standard/;
print header,
    start_html('A Simple Example'),
    h1('A Simple Example'),
    start_form,
    "What's your name? ",textfield('name'),p,
    "What's the combination?", p,
    checkbox_group(-method=>'GET',
    	 -name=>'words',
		   -values=>['eenie','meenie','minie','moe'],
		   -defaults=>['eenie','minie']), p,
    "What's your favorite color? ",
    popup_menu(-name=>'color',
	       -values=>['red','green','blue','chartreuse']),p,
    submit,
    end_form,
    hr;


for $i (param()) {
    print "<b>", $i, "</b>: ", param($i), "<br>\n";
}
