#!/usr/bin/perl

use autodie;
use CGI qw/:standard/;
my $query   = CGI->new;

print header,
    start_html('zapisywanie do pliku'),
    h1('zapisywanie do pliku'),
    start_form,
    filefield('uploaded_image'),
    submit,
    end_form,
    hr;

$upload_dir = "/home/patryk/Documents/Obsidian/vault/httpd/htdocs/upload";
$filename = $query->param('uploaded_image');
$type = $query->uploadInfo($filename)->{'Content-Type'};
unless ($type eq 'image/jpeg') {
    die "images ONLY!";
  }
$filename =~ s/.*[\/\\](.*)/$1/;
$upload_filehandle = $query->upload('uploaded_image');
  open UPLOADFILE, ">$upload_dir/$filename";
  while ( <$upload_filehandle> )
  {
    print UPLOADFILE;
  }
  close UPLOADFILE;
print <<END_HTML;

<DIV>
<P>Thanks for uploading your photo!</P>
<P>Your photo:</P>
<img src="/upload/$filename" border="0">
</DIV>
END_HTML
